<a href="https://colab.research.google.com/github/Arpit-Prasad-01/Bootcamp-Projects/blob/main/Bootcamp_3%264_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# SESSION 3 and 4: LISTS, DICTIONARIES, COMPLEX LOOPS & NUMPY FOUNDATION


# 1. LISTS & DICTIONARIES BASICS

# List


friends = ["arpit","akash","Krishna",55,False,True,98.8]
print(friends[0])

friends[0] = "harsh" # unlike strings [list( list always in square bracket) are mutable but string are immutable ,no modification of string]
print(friends[0])

friends[4]=True
print(friends[4])

print(friends[1:5])

# Ordered sequence list handling and indexing
subjects = ["Math", "Physics", "Chemistry", "Java", "ML"]
print(subjects[0])   # Positive Indexing
print(subjects[-1])  # Negative Indexing

numbers = [10, -5, 0, 8, -2, 15]
for num in numbers:
    if num > 0:
        print(num, "Positive")
    elif num < 0:
        print(num, "Negative")
    else:
        print(num, "Zero")


#  LOOPS (LIST OF DICTIONARIES)

students = [
    {"name": "Alice", "study_hours": 5, "attendance": 80, "marks": 85},
    {"name": "Bob", "study_hours": 3, "attendance": 70, "marks": 35}
]

for s in students:
    print("\nName:", s["name"])
    if s["marks"] > 75:
        print("Performance: Strong")
    elif s["marks"] >= 40:
        print("Performance: Need Improvement")
    else:
        print("Performance: Fail")

    if s["attendance"] < 75:
        print("Warning: Low Attendance")
    if s["study_hours"] < 4:
        print("Warning: Need More Study Time")




        # or

        students = []

for i in range(5):
    name = input("Enter student name: ")
    study_hours = int(input("Enter study hours: "))
    attendance = int(input("Enter attendance: "))
    marks = int(input("Enter marks: "))

    student = {
        "name": name,
        "study_hours": study_hours,
        "attendance": attendance,
        "marks": marks
    }

    students.append(student)


for s in students:
    print("\nName:", s["name"])

    if s["marks"] > 75:
        print("Performance: Strong")
    elif s["marks"] >= 40:
        print("Performance: Need Improvement")
    else:
        print("Performance: Fail")

    if s["attendance"] < 75:
        print("Warning: Low Attendance")

    if s["study_hours"] < 4:
        print("Warning: Need More Study Time")


transactions = [
    {"transaction_id": "TX101", "amount": 6200, "method": "Credit Card"},
    {"transaction_id": "TX102", "amount": 5500, "method": "Gift Card"},
    {"transaction_id": "TX103", "amount": 1200, "method": "Gift Card"},
    {"transaction_id": "TX104", "amount": 8000, "method": "Gift Card"},
    {"transaction_id": "TX105", "amount": 450, "method": "PayPal"}
]

flag_transactions = []
for tx in transactions:
    if tx['amount'] > 5000 and tx['method'] == 'Gift Card':
        flag_transactions.append(tx['transaction_id'])
print("\nFlagged Gift Card Transactions:", flag_transactions)


# NUMPY FOUNDATIONS (1D AND 2D MATRICES)-

import numpy as np

# 1D Array Analysis
arr = np.array([78, 91, 55, 72, 40, 88, 98, 81, 11, 23, 78, 88, 91, 96])
print("\nNumPy Array:", arr)
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)

# Indexing, Slicing,
print("Index 5 Element:", arr[5])
print("Slice [2:7]:", arr[2:7])


arpit
harsh
True
['akash', 'Krishna', 55, True]
Math
ML
10 Positive
-5 Negative
0 Zero
8 Positive
-2 Negative
15 Positive

Name: Alice
Performance: Strong

Name: Bob
Performance: Fail
Enter student name: Arpit
Enter study hours: 7
Enter attendance: 85
Enter marks: 89
Enter student name: Ankit
Enter study hours: 3
Enter attendance: 56
Enter marks: 67
Enter student name: Sunita
Enter study hours: 5
Enter attendance: 78
Enter marks: 80
Enter student name: Akash
Enter study hours: 8
Enter attendance: 79
Enter marks: 90
Enter student name: ARPI
Enter study hours: 5
Enter attendance: 68
Enter marks: 78

Name: Arpit
Performance: Strong

Name: Ankit
Performance: Need Improvement

Name: Sunita
Performance: Strong

Name: Akash
Performance: Strong

Name: ARPI
Performance: Strong

Flagged Gift Card Transactions: ['TX102', 'TX104']

NumPy Array: [78 91 55 72 40 88 98 81 11 23 78 88 91 96]
Dimensions: 1
Shape: (14,)
Size: 14
Index 5 Element: 88
Slice [2:7]: [55 72 40 88 98]


In [5]:
import numpy as np


# Creating NumPy array

arr = np.array([78, 91, 55, 72, 40, 88, 98, 81, 11, 23, 78, 88, 91, 96])

print(arr)


# Checking dimension and size

print(arr.ndim)
print(arr.shape)
print(arr.size)


# Indexing

print(arr[0])
print(arr[5])
print(arr[-1])


# Slicing

print(arr[2:7])
print(arr[:5])
print(arr[5:])


# Filtering

print(arr[arr > 75])
print(arr[arr < 40])


# Mathematical operations

print(arr + 5)
print(arr - 5)
print(arr * 2)


# Statistical operations

print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))


# Count values using condition

print(np.sum(arr > 75))


# 2D Array

grid = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


print(grid)


# Shape of matrix

print(grid.shape)


# Row indexing

print(grid[0])
print(grid[1])


# Column indexing

print(grid[:,0])
print(grid[:,1])


# Matrix indexing

print(grid[1,2])


# Matrix slicing

print(grid[0:2,0:2])


# Creating special arrays

print(np.zeros((3,3)))

print(np.ones((2,4)))

print(np.arange(1,10))

print(np.arange(1,10,2))


# Reshaping array

a = np.arange(1,10)

print(a.reshape(3,3))


# Random array

random_arr = np.random.randint(1,100,5)

print(random_arr)


# Sorting

print(np.sort(arr))

[78 91 55 72 40 88 98 81 11 23 78 88 91 96]
1
(14,)
14
78
88
96
[55 72 40 88 98]
[78 91 55 72 40]
[88 98 81 11 23 78 88 91 96]
[78 91 88 98 81 78 88 91 96]
[11 23]
[ 83  96  60  77  45  93 103  86  16  28  83  93  96 101]
[73 86 50 67 35 83 93 76  6 18 73 83 86 91]
[156 182 110 144  80 176 196 162  22  46 156 176 182 192]
70.71428571428571
98
11
990
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[1 2 3]
[4 5 6]
[1 4 7]
[2 5 8]
6
[[1 2]
 [4 5]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 4 23 16 31 30]
[11 23 40 55 72 78 78 81 88 88 91 91 96 98]
